### ISSUE TITLE
onnx inference code

### ISSUE THREAD

**Issue by chophilip21** [om-ai-lab/OmDet#23]
Hi, thank you for the awesome work. 

I know that you have prepared onnx converter code, but do you have any inference logic prepared for the onnx model as well? I have tried writing onnx inference pipeline based on your original torch model, but it's not so straight forward.

**Comment by jkl375** [comment]
https://github.com/om-ai-lab/OmDet/blob/main/omdet/omdet_v2_turbo/infer_model.py#L66
Thank you very much for your issue. 
1. The exported onnx model does not include image preprocessing and NMS post-processing. 
2. And because onnx requires the input to be a tensor, the x, labelfeats, task_feats, and task_mask inputs for OmDetV2TurboInfer are all tensors, and the batched_inputs input for OmDetV2Turbo is List[dict].

You need to modify your code based on the above two points.
